# Generated by Django 5.2.1 on 2025-05-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Xodim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ism", models.CharField(max_length=100)),
                ("familiya", models.CharField(max_length=100)),
                ("ishlayapti", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Topshiriq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomi", models.CharField(max_length=200)),
                ("tavsif", models.TextField()),
                ("bajarilgan", models.BooleanField(default=False)),
                ("tugash_sanasi", models.DateField(blank=True, null=True)),
                ("yaratilgan_vaqti", models.DateTimeField(auto_now_add=True)),
                ("yangilangan_vaqti", models.DateTimeField(auto_now=True)),
                (
                    "masullar",
                    models.ManyToManyField(related_name="topshiriqlar", to="ish.xodim"),
                ),
            ],
        ),
    ]
