# Generated by Django 5.2.3 on 2025-06-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ish', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='manzil',
            new_name='soato',
        ),
    ]
