# Generated by Django 5.2.1 on 2025-05-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ish", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topshiriq",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="topshiriqlar/"),
        ),
    ]
