# Generated by Django 5.2.3 on 2025-06-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ish', '0002_rename_manzil_customuser_soato'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelupload',
            name='tasdiqlangan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='excelupload',
            name='hisobot_davri',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='excelupload',
            name='hisobot_nomi',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='excelupload',
            name='xat_turi',
            field=models.CharField(max_length=50),
        ),
    ]
