# Generated by Django 5.2.1 on 2025-05-27 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ish", "0002_topshiriq_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="topshiriq",
            name="kirituvchi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kiritilgan_topshiriqlar",
                to="ish.xodim",
            ),
        ),
    ]
