# Generated by Django 5.2.1 on 2025-06-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ish", "0003_topshiriq_kirituvchi"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topshiriq",
            options={
                "ordering": ["-yaratilgan_vaqti"],
                "verbose_name": "Topshiriq",
                "verbose_name_plural": "Topshiriqlar",
            },
        ),
        migrations.RemoveField(
            model_name="topshiriq",
            name="kirituvchi",
        ),
        migrations.AlterField(
            model_name="topshiriq",
            name="masullar",
            field=models.ManyToManyField(
                blank=True, related_name="topshiriqlar", to="ish.xodim"
            ),
        ),
    ]
