# Generated by Django 5.2.3 on 2025-06-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ish', '0003_excelupload_tasdiqlangan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelupload',
            name='tasdiqlangan_vaqt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excelupload',
            name='pdf_fayli',
            field=models.FileField(blank=True, null=True, upload_to='jarima_xatlari'),
        ),
    ]
