# Generated by Django 5.2.1 on 2025-06-01 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ish", "0004_alter_topshiriq_options_remove_topshiriq_kirituvchi_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="topshiriq",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topshiriqlar",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
