# Generated by Django 5.2.3 on 2025-06-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ish', '0005_excelupload_dalolatnomasi_mavjudligi_dalolatnoma'),
    ]

    operations = [
        migrations.AddField(
            model_name='dalolatnoma',
            name='dalolatnoma_fayli',
            field=models.FileField(blank=True, null=True, upload_to='dalolatnomalar/'),
        ),
    ]
