# Generated by Django 5.2.1 on 2025-06-02 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ish", "0005_topshiriq_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Excelupload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("okpo", models.CharField(max_length=8)),
                ("inn", models.CharField(max_length=9)),
                ("soato", models.CharField(max_length=20)),
                ("nomi", models.CharField(max_length=400)),
                ("sababi", models.CharField(max_length=200)),
                ("opf", models.CharField(max_length=10)),
                (
                    "hisobot_nomi",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "hisobot_davri",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("faoliyatsiz", models.BooleanField(default=False)),
                (
                    "xat_turi",
                    models.CharField(
                        choices=[
                            ("ko'rsatma", "ko'rsatma"),
                            ("chaqiriq", "chaqiriq"),
                            ("sudga", "sudga"),
                        ],
                        default="ko'rsatma",
                        max_length=50,
                    ),
                ),
                ("xat_sanasi", models.DateField(blank=True, null=True)),
                ("aniqlangan_sanasi", models.DateTimeField(auto_now_add=True)),
                (
                    "kiritgan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excel_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
