# Generated by Django 5.2.1 on 2025-06-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ish", "0006_excelupload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="excelupload",
            name="aniqlangan_sanasi",
            field=models.DateField(auto_now_add=True),
        ),
    ]
