# Generated by Django 5.2.3 on 2025-06-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ish', '0006_dalolatnoma_dalolatnoma_fayli'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelupload',
            name='izoh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='excelupload',
            name='nazoratdan_chiqarilgan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dalolatnoma',
            name='izoh',
            field=models.TextField(blank=True, null=True),
        ),
    ]
