# Generated by Django 5.2.1 on 2025-06-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ish", "0007_alter_excelupload_aniqlangan_sanasi"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hisobot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomi", models.CharField(max_length=255)),
            ],
        ),
    ]
