# Generated by Django 5.2.3 on 2025-06-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ish', '0007_excelupload_izoh_excelupload_nazoratdan_chiqarilgan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dalolatnoma',
            name='nomi',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='dalolatnoma',
            name='tasdiqlangan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dalolatnoma',
            name='tasdiqlangan_vaqti',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
