# Generated by Django 5.2.1 on 2025-06-02 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ish", "0008_hisobot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hisobotdavri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("tugash_sanasi", models.DateField(blank=True, null=True)),
                (
                    "nomi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hisobot_davri",
                        to="ish.hisobot",
                    ),
                ),
            ],
        ),
    ]
