# Generated by Django 5.2.3 on 2025-06-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ish', '0008_dalolatnoma_nomi_dalolatnoma_tasdiqlangan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='yosh',
        ),
        migrations.AddField(
            model_name='excelupload',
            name='tekshirish_natijasi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
