# Generated by Django 5.2.3 on 2025-06-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ish', '0009_remove_customuser_yosh_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excelupload',
            options={'managed': True, 'verbose_name': 'korxona', 'verbose_name_plural': 'korxonalar'},
        ),
        migrations.AddField(
            model_name='excelupload',
            name='sudga_chiqarilgan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='excelupload',
            table='',
        ),
    ]
