# Generated by Django 5.2.1 on 2025-06-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ish", "0009_hisobotdavri"),
    ]

    operations = [
        migrations.AlterField(
            model_name="excelupload",
            name="xat_turi",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
