# Generated by Django 5.2.3 on 2025-06-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ish', '0010_alter_excelupload_xat_turi'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelupload',
            name='pdf_fayli',
            field=models.FileField(default=1, upload_to='jarima_xatlari'),
            preserve_default=False,
        ),
    ]
